#===========================================================================
# _untFcts Table: Where there is one unit per line, and each unit has:
#                 1) short abbreviated name;
#                 2) long descriptive name;
#                 3) base unit, namely the SI unit;
#                 4) scaling factor;
#                 5) additive factor.
#===========================================================================

_untFcts        = {

   "angstrom":       ( "decinanometer",        "m",    1.e-10,      0   ),
   "nm":	     ( "nanometer",            "m",    1.e-09,      0   ),
   "micron":	     ( "micrometer",           "m",    1.e-06,      0   ),
   "mil":	     ( "mil",                  "m",    2.54e-05,    0   ),
   "mm":	     ( "millimeter",           "m",    1.e-03,      0   ),
   "cm":	     ( "centimeter",           "m",    1.e-02,      0   ),
   "inch":	     ( "inch",                 "m",    0.0254,      0   ),
   "ft":	     ( "foot",                 "m",    0.3048,      0   ),
   "yd":	     ( "yard",                 "m",    0.9144,      0   ),
   "m":	             ( "meter",                "m",    1,           0   ),
   "rd":	     ( "rod",                  "m",    5.0292,      0   ),
   "km":	     ( "kilomemter",           "m",    1000.,       0   ),
   "mi":	     ( "mile",                 "m",    1609.344,    0   ),
   "nmile":	     ( "nautical mile",        "m",    1852,        0   ),
   "us":             ( "microsecond",          "sec",  1.e-6,       0   ),
   "ms":             ( "millisecond",          "sec",  0.001,       0   ),
   "sec":            ( "second",               "sec",  1,           0   ),
   "min":            ( "minute",               "sec",  60,          0   ),
   "hr":             ( "hour",                 "sec",  3600,        0   ),
   "day":            ( "day",                  "sec",  86400,       0   ),
   "week":           ( "week",                 "sec",  604800,      0   ),
   "month":          ( "month",                "sec",  2629744,     0   ),
   "yr":             ( "year",                 "sec",  31556926,    0   ),
   "mg":             ( "milligram",            "kg",   1.e-6,       0   ),
   "gr":             ( "grain",                "kg",   6.479891e-5, 0   ),
   "carat":          ( "carat",                "kg",   0.0002,      0   ),
   "g":              ( "gram",                 "kg",   0.001,       0   ),
   "dr":             ( "dram",                 "kg",   0.001771845, 0   ),
   "oz":             ( "ounce",                "kg",   0.028349523, 0   ),
   "ozt":            ( "ounce(Troy)",          "kg",   0.031103486, 0   ),
   "lb":             ( "pound",                "kg",   0.45359237,  0   ),
   "kg":             ( "kilogram",             "kg",   1,           0   ),
   "slug":           ( "slug",                 "kg",   14.59390294, 0   ),
   "shortton":       ( "shortton",             "kg",   907.18474,   0   ),
   "US ton":         ( "US ton",               "kg",   907.18474,   0   ),
   "metricton":      ( "kilokg",               "kg",   1000,        0   ),
   "ton":            ( "tonne",                "kg",   1000,        0   ),
   "Mg":             ( "Mega gram",            "kg",   1000,        0   ),
   "longton":        ( "longton",              "kg",   1016.046909, 0   ),
   "UK ton":         ( "UK ton",               "kg",   1016.046909, 0   ),

   "oR":             ( "rankine",              "K",
                       0.55555555555555555555555555555555555555556, 0   ),
   "oF":             ( "fahrenheit",           "K",
                       0.55555555555555555555555555555555555555556,
                       255.372222222222222222222222222222222222222      ),
   "K":              ( "kelvin",               "K",    1,           0   ),
   "oC":             ( "celsius",              "K",    1,      273.15   ),

   "dyne":           ( "dyne",                 "N",    1.e-5,       0   ),
   "N":              ( "newton",               "N",    1,           0   ),
   "lbf":            ( "pound force",          "N",   4.4482216152605, 0 ),

   "W/(m2-K/cm)":    ( "watt per(square meter-kelvin per centimeter)",
                       "W/m-K",                0.01,               0   ),
   "BTU/(hr-ft2-oF/in)": ("BTU per (hour-square foot-fahrenheit per inch)",
                          "W/m-K",             0.144131433801,     0   ),
   "KJ/hr-m-K":      ("kilojoule per hour-meter-kelvin",    "W/m-K",
                                        0.27777777777777777777,     0   ),
   "W/m-K":          ("watt per meter-kelvin",              "W/m-K",
                                                1,                  0   ),
   "J/m-sec-K":      ("joule per second-meter-kelvin",      "W/m-K",
                                                1,                  0   ),
   "Kcal/hr-m-oC":   ("kilocalorie per hour-meter-celsius", "W/m-K",
                                        1.16222222222222222000,     0   ),
   "BTU/hr-ft-oF":   ("BTU per hour-foot-fahrenheit",       "W/m-K",
                                        1.73073466699475065615,     0   ),
   "W/(in2-oF/in)":  ("watt per(square inch per fahrenheit per inch)",
                      "W/m-K",       70.86614173228346456692, 0 ),
   "W/cm-oC":        ("watt per centimeter-celsius",        "W/m-K",
                                                100,                0   ),
   "cal/sec-cm-oC":  ("calorie per second-centimeter-celsius",
                      "J/sec-m-K",              418.4,              0   ),
   "KW/m-K":         ("Kilo watt per meter-kelvin",         "W/m-K",
                                                1000,               0   ),
   "BTU/sec-ft-oF":  ("BTU per second-foot-fahrenheit",     "W/m-K",
                                      6230.64480118110236214000,    0   ),
   "MW/m-K":         ("mega watt per meter-kelvin",         "W/m-K",
                                                1e+6,               0   ),
   "W/m2-K":         ("watt per (square meter-kelvin)",     "J/m2-sec-K",
                                                1,               0   ),
   "KJ/hr-m2-K":     ("kilojoule per (hour-sqaure meter-kelvin)",
                      "J/m2-sec-K",   0.27777777777777777777,      0   ),
   "J/m2-sec-K":     ("joule per (square meter-second-kelvin)",
                      "J/m2-sec-K",             1,                0   ),
   "Kcal/hr-m2-oC":  ("kilocalorie per (hour-square meter-celsius",
                      "J/m2-sec-K",   1.16222222222222222000,     0   ),
   "BTU/hr-ft2-oF":  ("BTU per (hour-square foot-fahrenheit)",
                      "J/m2-sec-K",   5.67826334315863076169,     0   ),
   "W/in2-oF":       ("watt per(square inch per fahrenheit)",
                      "J/m2-sec-K",   2790.00558001116002232003,  0   ),
   "W/cm2-oC":       ("watt per (square centimeter-celsius)",
                      "J/m2-sec-K",             10000,            0   ),
   "cal/sec-cm2-oC": ("calorie per (second-square centimeter-celsius)",
                      "J/m2-sec-K",             41868.0,          0   ),
   "KW/m2-K":        ("Kilo watt per (square meter-kelvin)",
                      "J/m2-sec-K",             1000,             0   ),
   "BTU/sec-ft2-oF": ("BTU per (second-square foot-fahrenheit)",
                      "J/m2-sec-K",   20441.74803537107074214147, 0   ),
   "MW/m2-K":        ("mega watt per (sqaure meter-kelvin)",
                      "J/m2-sec-K",             1e+6,             0   ),

   "dyne/cm2":       ("dyne per square centimeter",         "N/m2",
                                                0.1,              0   ),
   "N/m2":           ("newton per square meter",            "N/m2",
                                                1,                0   ),
   "pa":             ("pascal",                "N/m2",      1,    0   ),
   "pdl/ft2":        ("poundal per square foot",            "N/m2",
                                         1.48816394382788765577,  0   ),
   "mm H2O":         ("millimeter H2O",                     "N/m2",
                                          9.806379738,            0   ),
   "kgf/m2":         ("kilogram force per square meter",    "N/m2",
                                                9.80665,          0   ),
   "lbf/ft2":        ("pound force per square foot",        "N/m2",
                                   47.88025898033584261604,       0   ),
   "cm H2O":         ("centimeter H2O",        "N/m2",      98.0665,0   ),
   "gf/cm2":         ("gram force per square centimeter",   "N/m2",
                                                98.0665,             0  ),
   "mbar":           ("millibar",               "N/m2",     100,    0   ),
   "torr":           ("torr",                   "N/m2",
                                                133.322368421,      0   ),
   "mm Hg":          ("millimeter Hg",          "N/m2",
                                                133.3223684211,     0   ),
   "in-H2O (60 oF)":  ("inch-H2O (60 oF)",      "N/m2",     248.84, 0   ),
   "in-H2O (39.2 oF)":("inch-H2O (39.2 oF)",    "N/m2",     249.082,0   ),
   "in H2O":          ("inch H2O",              "N/m2",
                                                249.088916667,      0   ),
   "KPa":             ("Kilo Pascal",           "N/m2",     1.e+3,  0   ),
   "cm Hg":           ("centimeter Hg",         "N/m2",
                                                1333.223684211,     0   ),
   "cm-mercury(0 oC)":("cm-mercury(0 oC)",      "N/m2",
                                                1333.22,            0   ),
   "ft H2O":          ("foot H2o",              "N/m2",     2989.067,0  ),
   "in-mercury(60 oF)":("inch-mercury(60 oF)",  "N/m2",     3376.85,0   ),
   "in Hg":           ("inch Hg",               "N/m2",
                                                3386.38833333,      0   ),
   "in-mercury(32 oF)": ("inch-mercury(32 oF)", "N/m2",     3386.389,0  ),
   "lbf/in2":         ("pound force per square inch",       "N/m2",
                                                6894.757293168,     0   ),
   "PSI":             ("PSI",                   "N/m2",
                                                6894.757293168,     0   ),
   "m H2O":           ("meter H2O",             "N/m2",     9806.65,0   ),
   "N/cm2":           ("newton per square centimeter",      "N/m2",
                                                10000,              0   ),
   "ft Hg":           ("foot Hg",               "N/m2",
                                                40636.66,           0   ),
   "kgf/cm2":         ("kilogram force per square centimeter",
    "N/m2",                                     98066.5,            0   ),
   "bar":             ("bar",                   "N/m2",
                                                1e+5,               0   ),
   "atm":             ("atmosphere",            "N/m2",
                                                101325,             0   ),
   "m Hg":            ("meter Hg",              "N/m2",
                                                133322.368421053,   0   ),
   "MPa":             ("Mega Pascal",           "N/m2",
                                                1.e+6,              0   ),
   "N/mm2":           ("newton per square millimeter",     "N/m2",
                                                1.e+6,              0   ),
   "kgf/mm2":         ("kilogram force per square millimeter",
    "N/m2",                                     9806650,            0   ),

   "cm/hr":           ("centimeters per hour",  "m/sec",
                                            0.00000277777777777777, 0   ),
   "in/hr":           ("inches per hour",       "m/sec",
                                            0.00000705555555555555, 0   ),
   "ft/hr":           ("feet per hour",         "m/sec",
                                            0.00008466666666666666, 0   ),
   "furlong/fortnight": ("furlong per fortnight",          "m/sec",
                                            0.00016630952380952380, 0   ),
   "cm/min":          ("centimeters per minute","m/sec",
                                            0.00016666666666666666, 0   ),
   "m/hr":           ("meter per hour",         "m/sec",
                                            0.00027777777777777777, 0   ),
   "in/min":         ("inches per minute",      "m/sec",
                                            0.00042333333333333333, 0   ),
   "mm/sec":         ("millimeters per second", "m/sec",
                                                0.001,              0   ),
   "ft/min":         ("feet per minute",        "m/sec",
                                                0.00508,            0   ),
   "cm/sec":         ("centimeters per second", "m/sec",
                                                0.01,               0   ),
   "m/min":          ("meters per minute",      "m/sec",
                                            0.01666666666666666666, 0   ),
   "in/sec":         ("inches per second",      "m/sec",
                                                0.0254,             0   ),
   "km/hr":          ("kilometers per hour",    "m/sec",
                                            0.27777777777777777000, 0   ),
   "ft/sec":         ("feet per second",        "m/sec",
                                                0.3048,             0   ),
   "mile/hr":        ("miles per hour",         "m/sec",
                                                0.44704,            0   ),
   "knots":          ("knots",                  "m/sec",
                                                5.144444444e-1,     0   ),
   "yd/sec":         ("yard per second",        "m/sec",
                                                9.14400e-1,         0   ),
   "m/sec":          ("meters per second",      "m/sec",
                                                1,                  0   ),
   "mach":           ( "mach",                  "m/sec",
                                                331.622,            0   ),

   "g/liter":        ("grams per liter",        "kg/m3",
                                                1,                  0   ),
   "kg/m3":          ("kilograms per cubic meter",          "kg/m3",
                                                1,                  0   ),
   "SG(rel. Air)":   ("SG(rel. Air)",           "kg/m3",
                                                1.222569295,        0   ),
   "lb/ft3":         ("lb per cubic foot",      "kg/m3",
                                                16.018463374,       0   ),
   "lb/UKgal":       ("lb per UK gallon",       "kg/m3",
                                                99.776420423,       0   ),
   "lb/USgal":       ("lb per US gallon",       "kg/m3",
                                                119.826427317,      0   ),
   "slug/ft3":       ("slug per cubic foot",    "kg/m3",
                                                515.378818393,      0   ),
   "g/cm3":          ("grams per cubic centimeter",         "kg/m3",
                                                1000,               0   ),
   "kg/liter":       ("kilograms per liter",    "kg/m3",
                                                1000,               0   ),
   "metricton/m3":   ("metrictons per cubic meter",         "kg/m3",
                                                1000,               0   ),
   "SG(rel. Water)": ("SG(rel. Water)",         "kg/m3",
                                                1000,               0   ),
   "oBaume":         ("oBaume",                 "kg/m3",
                                                1006.944444444,     0   ),
   "oAPI":           ("oAPI",                   "kg/m3",
                                                1067.924528302,     0   ),
   "longton/yd3":    ("long-tons per cubic yard","kg/m3",
                                        1328.93918387902392602685,  0   ),
   "lb/in3":         ("lb per cubic inch",      "kg/m3",
                                        27679.90471020312119364396, 0   ),
   "ton/ft3":        ("shorttons per cubic foot","kg/m3",
                                        32036.92674792027915931014, 0   ),
   "kg/cm3":         ("kilogram per cubic centimeter",      "kg/m3",
                                                1e+6,               0   ),

   "ft/hr2":         ("foot per square hour",    "m/sec2",
                                            0.00000002351851851851, 0   ),
   "m/hr2":          ("meter per square hour",   "m/sec2",
                                            0.00000007716049382716, 0   ),
   "ft/min2":        ("foot per square minute",  "m/sec2",
                                            0.00008466666666666666, 0   ),
   "mm/sec2":        ("milimeter per square second",         "m/sec2",
                                                1e-3,               0   ),
   "gal":            ("gal",                    "m/sec2",
                                                0.01,               0   ),
   "cm/sec2":        ("centimeter per square second",        "m/sec2",
                                                0.01,               0   ),
   "in/sec2":        ("inch per square second",  "m/sec2",
                                                2.54e-2,            0   ),
   "ft/sec2":	     ("feet per second squared","m/sec2",
                                                 0.3048,            0	),
   "miles/hr2":      ("miles per square hour",   "m/sec2",
                                            .00012417777777777777,  0   ),
   "m/sec2":	     ("meters per second squared",          "m/sec2",
                                                1,                  0   ),
   "grav":           ("gravitation",            "m/sec2",
                                                9.80665,            0   ),
   "km/sec2":        ("kilo meter per square second",        "m/sec2",
                                                1000,               0   ),
   "miles/sec2":     ("miles per square second", "m/sec2",
                                                1609.344,           0   ),


   "second":         ("arc-second",             "deg",
						3598.55158502, 0 	),
   "minute":         ("arc-minute",             "deg",
						59.9758597504, 	0 	),
   "centrad":        ("centrad",                "deg",
						1.74532925199, 0 	),
   "grad":           ("grad",                   "deg",
						1.11066406945, 0 	),
   "deg":            ("deg",                 "deg",
						1.0, 0 			),
   "circle":         ("circle",                 "deg",
						0.00277777777778, 0 	),
   "quad":           ("quadrant",               "deg",
						0.0111111111111, 0 	),
   "rad":            ("rad",               "deg",
						57.2957795131, 0 	),

   "second/sec":     ("arc-seconds per second", "rad/sec",
                                           0.00000485008818342151,  0   ),
   "minute/sec":     ("arc-minutes per second", "rad/sec",
                                           0.00029100529100529100,  0   ),
   "deg/sec":        ("degrees per second",     "rad/sec",
                                           0.01746031746031746031,  0   ),
   "rad/sec":        ("radians per second",     "rad/sec",
                                                1,                  0   ),
   "quad/sec":       ("quadrants per second",   "rad/sec",
                                           1.57142857142857142857,  0   ),
   "circle/sec":     ("circles per second",     "rad/sec",
                                           6.28571428571428571428,  0   ),
   "RPM":	     ("revolutions per minute",	"rad/sec",
		   			   0.10471975511965977462,  0	),

   "second/sec2":    ("arc-seconds per second squared",
    "rad/sec2",                            0.00000485008818342151,  0   ),
   "minute/sec2":    ("arc-minutes per second squared",
    "rad/sec2",                            0.00029100529100529100,  0   ),
   "deg/sec2":       ("degrees per second squared",
    "rad/sec2",                            0.01746031746031746031,  0   ),
   "rad/sec2":       ("radians per second squared",
    "rad/sec2",                                 1,                  0   ),
   "quad/sec2":      ("quadrants per second squared",
    "rad/sec2",                            1.57142857142857142857,  0   ),
   "circle/sec2":    ("circles per second squared",
    "rad/sec2",                            6.28571428571428571428,  0   ),

   "lb-ft2/sec":     ("pound foot squared per second",
    "kg-m2/sec",                                0.0421401100938048, 0   ),
   "kg-m2/sec":      ("kilogram meter squared per second",
    "kg-m2/sec",                                1,                  0   ),

   "lb-ft2/sec2":    ("pound foot squared per second squared",
    "kg-m2/sec2",                               0.0421401100938048, 0   ),
   "kg-m2/sec2":     ("kilogram meter squared per second squared",
    "kg-m2/sec2",                               1,                  0   ),

   "attostoke":     ("attostoke",               "m2/sec",
                                                1e-22,              0   ),
   "femtostoke":    ("femtostoke",              "m2/sec",
                                                1e-19,              0   ),
   "picostoke":     ("picostoke",               "m2/sec",
                                                1e-16,              0   ),
   "nanostoke":     ("nanostoke",               "m2/sec",
                                                1e-13,              0   ),
   "microstoke":    ("microstoke",              "m2/sec",
                                                1e-10,              0   ),
   "millistoke":    ("millistoke",              "m2/sec",
                                                1e-7,               0   ),
   "centistoke":    ("centistoke",              "m2/sec",
                                                0.000001,           0   ),
   "mm2/sec":       ("square millimeter/second","m2/sec",
                                                0.000001,           0   ),
   "decistoke":     ("decistoke",               "m2/sec",
                                                0.00001,            0   ),
   "cm2/sec":       ("square centimeter/second","m2/sec",
                                                0.0001,             0   ),
   "stoke":         ("stoke",                   "m2/sec",
                                                0.0001,             0   ),
   "dekastoke":     ("dekastoke",               "m2/sec",
                                                0.001,              0   ),
   "hectostoke":    ("hectostoke",              "m2/sec",
                                                0.01,               0   ),
   "ft2/sec":       ("square foot/second",      "m2/sec",
                                                0.09290304,         0   ),
   "kilostoke":     ("kilostoke",               "m2/sec",
                                                0.1,                0   ),
   "m2/sec":        ("square meter/second",     "m2/sec",
                                                1,                  0   ),
   "megastoke":     ("megastoke",               "m2/sec",
                                                100,                0   ),
   "gigastoke":     ("gigastoke",               "m2/sec",
                                                100000,             0   ),
   "terastoke":     ("terastoke",               "m2/sec",
                                                1e8,                0   ),
   "petastoke":     ("petastoke",               "m2/sec",
                                                1e11,               0   ),
   "exastoke":      ("exastoke",                "m2/sec",
                                                1e14,               0   ),

   "erg/g":         ("erg/g",                   "J/kg",
                                                1e-4,               0   ),
   "J/kg":          ("joule per kilogram",      "J/kg",
                                                 1,                 0   ),
   "ft-lbf/lb":     ("ft-lbf/lb",               "J/kg",
                                       2.98906691982495208197,      0   ),
   "kgf-m/kg":      ("kgf-m/kg",                "J/kg",
                                                9.80665,            0   ),
   "J/g":           ( "Joule per gram",         "J/kg",
                                                1000,               0   ),
   "MJ/tonne":      ("Mega Joule per tonne",    "J/kg",
                                                1000,               0   ),
   "kJ/kg":         ("kilojoule per kilogram",  "J/kg",
                                                1000,               0   ),
   "BTU/lb":        ("BTU/lb",                  "J/kg",
                                      2326.000000,    0   ),
   "cal/g":         ("calorie per gram",         "J/kg",
                                                4186.8,             0   ),
   "CHU/lb":        ("CHU/lb",                  "J/kg",
                                                4186.8,             0   ),
   "kcal/kg":       ("kilo calorie per kilo gram","J/kg",
                                                4186.8,             0   ),
   "MJ/kg":         ("Mega Joule per kilo gram","J/kg",
                                                1e+6,               0   ),

   "g/hr-m2":       ("gram per hour square meter",
    "kg/m2sec",                            0.00000027777777777777,  0   ),
   "g/min-m2":      ("gram per minute square meter",
    "kg/m2sec",                            0.00001666666666666666,  0   ),
   "g/sec-cm2":     ("gram per second square centimeter",
    "kg/m2sec",                                 10,                 0   ),
   "kg/hr-m2":      ("kilogram per hour square meter",
    "kg/m2sec",                        0.00027777777777777777,      0   ),
   "kg/hr-ft2":     ("kilogram per hour square foot",
    "kg/m2sec",                        0.00298997511575270055,      0   ),
   "kg/m2sec":      ("kilogram per square meter second",
    "kg/m2sec",                                 1,                  0   ),
   "lb/hr-ft2":     ("lb/hr-ft2",               "kg/m2sec",
                                       0.00135622989899529175,      0   ),
   "lb/min-ft2":    ("lb/min-ft2",              "kg/m2sec",
                                       0.08137379393971750902,      0   ),
   "lb/ft2sec":     ("lb/ft2s",                 "kg/m2sec",
                                       4.88242763638305054387,      0   ),

   "erg/sec-cm3":   ("erg/sec-cm3",             "W/m3",
                                                0.1,                0   ),
   "W/m3":          ("watt per cubic meter",    "W/m3",
                                                1,                  0   ),
   "kcal/hr-m3":    ("kilocalorie per hour cubic meter",
    "W/m3",                                     1.1630000000,       0   ),
   "BTU/hr-ft3":    ("BTU/hr-ft3",              "W/m3",
                                       10.34970717256968278234,     0   ),

   "kg/m-hr":       ("kilogram per meter-hour", "kg/m-sec",
                                            0.00027777777777777777, 0   ),
   "lb/ft-hr":      ("pound per foot-hour",     "kg/m-sec",
                                            0.00041337887321376494, 0   ),
   "cP":            ("cP",                      "kg/m-sec",
                                                0.001,              0   ),
   "poise":         ("poise",                   "kg/m-sec", 0.1,    0   ),
   "g/cm-sec":      ("gram per centimeter-second",
    "kg/m-sec",                                 0.1,                0   ),
   "dyne-sec/cm2":  ("dyne-second per square centimeter",
    "kg/m-sec",                                 0.1,                0   ),
   "kg/m-sec":      ("kilogram per meter-second","kg/m-sec",
                                                1,                  0   ),
   "pa-sec":        ("pascal-second",           "kg/m-sec",  1,     0   ),
   "N-sec/m2":      ("N-second per square meter","kg/m-sec",
                                                1,                  0   ),
   "lb/ft-sec":     ("pound per foot-second",   "kg/m-sec",
                                     1.48816394356955380577,        0   ),
   "poundal-sec/ft2":("poundal-second per square foot",
    "kg/m-sec",                      1.48816394356955380577,        0   ),

   "kgf-sec/m2":     ("kilogram force-second per square meter",
    "kg/m-sec",                                 9.80665,            0   ),
   "slugs/ft-sec":   ("slugs per foot-second",  "kg/m-sec",
                                    47.88025898950131233595,        0   ),
   "lbf-sec/ft2":    ("pound force-second per square foot",
    "kg/m-sec",                     47.88025898950131233595,        0   ),
   "lbf-sec/in2":    ("pound force-second per square inch",
    "kg/m-sec",                      6894.75729448818897637680,     0   ),

   "erg/g-C":        ("erg per gram-celsius",   "J/kg-K",   1.0E-04,0   ),
   "J/kg-K":         ("joule per kilogram-kelvin",
                      "J/kg-K",                 1,                  0   ),
   "m2/sec2-K":      ("square meter per square second-kelvin",
                      "J/kg-K",                 1,                  0   ),
   "ft-lbf/lbm-F":   ("foot-lbf per lbm-fahrenheit",
                      "J/kg-K",     5.38032045568491374754,         0   ),
   "J/g-k":          ("joule per gram-celsius", "J/kg-K",   1000,   0   ),
   "J/g-C":          ("joule per gram-kelvin",  "J/kg-K",   1000,   0   ),
   "cal/g-C":        ("calorie per gram-celsius",
                      "J/kg-K",                 4186.8,       0   ),
   "BTU/lb-F":       ("britishthermalunit per pound-fahrenheit",
                      "J/kg-K",                 4186.8,       0   ),

   "dyn/cm":         ("dyne per centimeter",    "N/m",      0.001,  0   ),
   "mN/m":           ("milinewton per meter",   "N/m",      0.001,  0   ),
   "gf/cm":          ("gram force per centimeter","N/m",    0.980665, 0 ),
   "N/m":            ("newton per meter",       "N/m",      1,      0   ),
   "lbf/ft":         ("pound force per inch",   "N/m",
                                     14.59390293635170603674,       0   ),
   "lbf/in":         ("pound force per inch",   "N/m",
                                  175.12683523622047244088,         0   ),
   "dyn.cm":         ("dyne centimeter",        "N.m",      1e-7,   0   ),
   "gf.cm":          ("gram-force centimeter",  "N.m",
                                                9.80665e-005,       0   ),
   "mN.m":           ("millinewton metr",       "N.m",      0.001,  0   ),
   "ozf.in":         ("ounce-force inch",       "N.m",
                                              0.00706155181381250,  0   ),
   "ozf.ft":         ("ounce-force foot",       "N.m",
                                              0.08473862176575000,  0   ),
   "lbf.in":         ("pound-force inch",       "N.m",
                                                0.1129848290210,    0   ),
   "N.m":            ("newton meter",           "N.m",      1,      0   ),
   "lbf.ft":         ("pound-force foot",       "N.m", 1.3558179482520,0 ),
   "kgf.m":          ("kilogram-force meter",   "N.m",      9.80665,0   ),
   "kN.m":           ("kilonewton meter",       "N.m",      1000,   0   ),

   "mm2/sec":        ("square millimeter per second",
                      "m2/sec",                 1e-6,               0   ),
   "ft2/hr":         ("square foot per hour",   "m2/sec", .0000258064, 0 ),
   "cm2/sec":        ("square centimeter per second",
                      "m2/sec",                 1e-4,               0   ),
   "m2/hr":          ("square meter per hour",  "m2/sec",
		                            0.00027777777777777777, 0   ),
   "ft2/sec":        ("square foot per second", "m2/sec", 0.09290304, 0 ),
   "m2/sec":         ("square meter per second","m2/sec",   1,      0   ),
   "Mlit/day":       ("Mega liter per day",     "m3/sec",
                      0.01157407407407407407,        0   ),
   "lit/hr":         ("liter per hour",         "m3/sec",
                                              0.00000027777777777777, 0 ),
   "barrel(oil)/day":("barrel(oil) per day",    "m3/sec",
                                              0.00000184013072800925, 0 ),
   "gal(UK)/hr":     ("gal(UK) per hour",       "m3/sec",
                                              0.00000126280285611111, 0 ),
   "gal(US)/hr":     ("gal(US) per hour",       "m3/sec",
                                              0.00000105150327333333, 0 ),
   "barrel(oil)/hr": ("barrel(oil) per hour",   "m3/sec",
                                              0.00004416313747222222, 0 ),
   "lit/min":        ("liter per minute",       "m3/sec",
                                              0.00001666666666666666, 0 ),
   "ft3/min":        ("cubic foot per minute",  "m3/sec",
                                              0.0004719474432,        0 ),
   "gal(US)/min":     ("gal(US) per minute",    "m3/sec",
                                              0.0000630901964, 0 	),
   "m3/hr":          ("cubic meter per hour",   "m3/sec",
                                              0.00027777777777777777, 0 ),
   "gal(UK)/sec":    ("gal(UK) per second",     "m3/sec",
                                              0.004546090282,         0 ),
   "gal(US)/sec":    ("gal(US) per second",     "m3/sec",
                                              0.003785411784,         0 ),
   "lit/sec":        ("liter per second",       "m3/sec",   .001,   0   ),
   "ft3/sec":        ("cubic foot per second",  "m3/sec",
                                              0.028316846592,       0   ),
   "m3/sec":         ("cubic meter per second", "m3/sec",   1,      0   ),
   "W/m2":          ("Watt per square meter",   "W/m2",     1,      0   ),
   "kcal/m2-hr":    ("kilo calorie per square meter-hour",
                     "W/m2",                                1.16300,0   ),
   "BTU/ft2-hr":    ("BTU per square foot-hour","W/m2",
		                             3.15459074619923931205,0   ),
   "CHU/ft2-hr":    ("CHU per square foot-hour","W/m2",  5.678263398,0  ),
   "pcu/ft2-hr":    ("pcu/ft2-hr",              "W/m2",  5.678263398,0  ),
   "kcal/ft2-hr":   ("kilo calorie per square foot-hour",
                     "W/m2",                12.51842781463340704000,0   ),
   "KW/m2":         ("Kilo Watt per square meter","W/m2",   1000,   0   ),
   "W/cm2":         ("Watt per square centimeter","W/m2",   1e4,    0   ),
   "BTU/ft2-sec":   ("BTU per square foot-second",
                     "W/m2",    11356.52668631726152341193,         0   ),
   "cal/cm2-sec":   ("calorie per square centimeter-second",
                     "W/m2",                    4.18680e+4,         0   ),

   "BTU/hr":        ("BTU per hour",            "W",
                                     0.29307107027777777777,        0   ),
   "J/sec":         ("Joule per second",        "W",        1,      0   ),
   "W":             ("Watt",                    "W",        1,      0   ),
   "kcal/hr":       ("kilo calorie per hour",    "W",
                                                1.163,        0   ),
   "cal/sec":       ("calorie per second",     "W",        4.1868,  0   ),
   "BTU/min":       ("BTU per minute",          "W",
                                     17.58426421666666666666,       0   ),
   "kcal/min":      ("kilo calorie per minute",  "W",
                                                69.78,       0   ),
   "kJ/sec":        ("kilo Joule per second",   "W",        1e3,    0   ),
   "kW":            ("kilo Watt",               "W",        1e3,    0   ),
   "BTU/sec":       ("BTU per second",          "W",
                                                1055.055852620,     0   ),
   "CHU/sec":       ("CHU per second",          "W",
                                                1899.100534716,     0   ),
   "kcal/sec":      ("kilo calorie per second",  "W",     4186.8,   0   ),
   "MJ/sec":        ("Mega Joule per second",   "W",        1e6,    0   ),
   "MW":            ("Mega Watt",               "W",        1e6,    0   ),

   "W/m2-K4":       ("watt per square meter-quad kelvin",
                     "W/m2-K4",                 1,                  0   ),

   "1/yr":          ("inverse year",            "1/sec",
                                     0.00000003170979198376,        0   ),
   "1/month":       ("inverse month",           "1/sec",
                                     0.00000038580246913580,        0   ),
   "1/week":        ("inverse week",            "1/sec",
                                     0.00000165343915343915,        0   ),
   "1/day":         ("inverse day",             "1/sec",
                                     0.00001157407407407407,        0   ),
   "1/hr":          ("inverse hour",            "1/sec",
                                     0.00027777777777777777,        0   ),
   "1/min":         ("inverse minute",          "1/sec",
                                     0.01666666666666666666,        0   ),
   "1/sec":         ("inverse second",          "1/sec",    1,      0   ),
   "1/ms":          ("inverse millisecond",     "1/sec",    1000,   0   ),
   "1/us":          ("inverse microsecond",     "1/sec",    1.e6,   0   ),

   "mm2/kgf":       ("square millimeter per kilogram force","m2/N",
                      1.0197162129779282425700927431896e-7,         0   ),
   "mm2/N":         ("square millimeter per newton",
                     "m2/N",                    1.e-6,              0   ),
   "1/MPa":         ("inverse Mega Pascal",     "m2/N",     1.e-6,  0   ),
   "1/m Hg":        ("inverse meter Hg",        "m2/N",
                     7.500616827041676780925619820681e-6,           0   ),
   "1/atm":         ("inverse atmosphere",      "m2/N",
                      9.8692326671601283000246730816679e-6,         0   ),
   "1/bar":         ("inverse bar",             "m2/N",     1e-5,   0   ),
   "cm2/kgf":       ("square centimeter per kilogram force",
                     "m2/N",1.0197162129779282425700927431896e-5,   0   ),
   "1/ft Hg":       ("inverse foot Hg",         "m2/N",
                      2.4608321648481937245826797773242e-5,         0   ),
   "cm2/N":         ("square centimeter per newton",
                     "m2/N",                    .0001,              0   ),
   "1/m H2O":       ("inverse meter H2O",       "m2/N",
                     1.0197162129779282425700927431896e-4,          0   ),
   "1/PSI":         ("inverse PSI",             "m2/N",
                     1.4503773773021681621379787920492e-4,          0   ),
   "in2/lbf":       ("square inch per pound force",         "m2/N",
                      1.4503773773021681621379787920492e-4,         0   ),
   "1/in-mercury(32 oF)":("inverse inch-mercury(32 oF)",    "m2/N",
                          2.9529980164712323362732397252649e-4,     0   ),
   "1/in Hg":       ("inverse inch Hg",         "m2/N",
                     2.9529985978207392030721232888757e-4,          0   ),
   "1/in-mercury(60 oF)":("inverse inch-mercury(60 oF)",    "m2/N",
                          2.9613397100848423826939307342642e-4,     0   ),
   "1/ft H2O":      ("inverse foot H2o",       "m2/N",
                      3.3455255435893541362572334444159e-4,         0   ),
   "1/cm-mercury(0 oC)":("inverse cm-mercury(0 oC)",        "m2/N",
                         7.5006375541921063290379682272993e-4,      0   ),
   "1/cm Hg":       ("inverse centimeter Hg",  "m2/N",
                      7.5006168270390325960446740175331e-4,         0   ),
   "1/KPa":         ("inverse Kilo Pascal",     "m2/N",     .001,   0   ),
   "1/in H2O":      ("inverse inch H2O",        "m2/N",
                      0.0040146306523018525437505390778544,         0   ),
   "1/in-H2O (39.2 oF)":("inverse inch-H2O (39.2 oF)",      "m2/N",
                         0.0040147421331127901654876707269092,      0   ),
   "1/in-H2O (60 oF)":("inverse inch-H2O (60 oF)",          "m2/N",
                       0.004018646519852113808069442211863,         0   ),
   "1/mm Hg":       ("inverse millimeter Hg",  "m2/N",
                     0.0075006168270390325960446740175331,          0   ),
   "1/torr":        ("inverse torr",            "m2/N",
                     0.0075006168270446585213232843458263,          0   ),
   "1/mbar":        ("inverse millibar",        "m2/N",    0.01,    0   ),
   "cm2/gf":        ("square centimeter per gram force",   "m2/N",
                     0.010197110138986611194387510579502,           0   ),
   "1/cm H2O":      ("inverse entimeter H2O",              "m2/N",
                     0.010197162129779282425700927431896,           0   ),
   "ft2/lbf":       ("square foot per pound force",        "m2/N",
                     0.020885434233296621989157001840427,           0   ),
   "m2/kgf":        ("square meter per kilogram force",    "m2/N",
                     0.10197162129779282425700927431896,            0   ),
   "1/mm H2O":      ("inverse millimeter H2O", "m2/N",   0.10197162,0   ),
   "ft2/pdl":       ("square foot per poundal","m2/N",   0.67204301,0   ),
   "1/pa":          ("inverse pascal",         "m2/N",   1,         0   ),
   "m2/N":          ("square meter per newton","m2/N",   1,         0   ),
   "cm2/dyne":      ("square centimeter per dyne","m2/N",10,        0   ),

   "1/K" :          ("inverse Kelvin",         "1/K",    1,         0   ),
   "1/oR":          ("inverse Rankine",        "1/K",  1.8,         0   ),

   "lb/day": ("pound per day",      "kg/sec",0.00000524991168981481, 0 ),
   "g/min":  ("gram per minute",    "kg/sec",0.00001666666666666666666,0 ),
   "kg/day": ("kilogram per day",   "kg/sec",0.00001157407407407407, 0 ),
   "kg/hr":  ("kilogram per hour",  "kg/sec",0.00027777777777777777, 0 ),
   "lb/hr":  ("pound per hour",     "kg/sec",0.00012599788055555555, 0 ),
   "lb/min": ("pound per minute",   "kg/sec",0.00755987283333333333, 0 ),
   "g/sec":  ("gram per second",    "kg/sec",0.001,                  0 ),
   "kg/min": ("kilogram per minute","kg/sec",0.01666666666666666666, 0 ),
   "lb/sec": ("pound per second",   "kg/sec",0.45359237,             0 ),
   "kg/sec": ("kilogram per second","kg/sec",1,                      0 ),


# NEW VARIABLES: PRASHANT
   "1/oC":          ("inverse Celcius",        "1/K",    1,         0   ),
   "1/oF":          ("inverse Fahrenheit",     "1/K",  1.8,         0   ),

# MASS HEAT SOURCE
   "erg/sec-gm":   ("erg/sec-gm",             "W/kg",
                                                0.0001,              0 ),
   "W/kg":          ("watt per kilogram",     "W/kg",
                                                1,                   0 ),
   "kcal/hr-kg":    ("kilocalorie per hour kilogram",
    "W/kg",                                     1.1630000000,        0 ),
   "BTU/hr-lb":    ("BTU/hr-lb",              "W/kg",
                                       0.64611111111111111111,       0 ),
   "cal/sec-gm":    ("calorie per sec gram",
    "W/kg",                                     4186.8000000,        0 ),

# VOLUME SPECIES SOURCE
   "g/hr-m3":       ("gram per hour cubic meter",
    "kg/m3sec",                            0.00000027777777777777,   0 ),
   "g/min-m3":      ("gram per minute cubic meter",
    "kg/m3sec",                            0.00001666666666666666,   0 ),
   "g/sec-cm3":     ("gram per second cubic centimeter",
    "kg/m3sec",                               1000,                  0 ),
   "kg/hr-m3":      ("kilogram per hour cubic meter",
    "kg/m3sec",                        0.00027777777777777777,       0 ),
   "kg/hr-ft3":     ("kilogram per hour cubic foot",
    "kg/m3sec",                        0.00980962964485794143,       0 ),
   "kg/m3sec":      ("kilogram per cubic meter second",
    "kg/m3sec",                                 1,                   0 ),
   "lb/hr-ft3":     ("lb/hr-ft3",               "kg/m3sec",
                                       0.00444957315943337188,       0 ),
   "lb/min-ft3":    ("lb/min-ft3",              "kg/m3sec",
                                       0.26697438956600232618,       0 ),
   "lb/ft3sec":     ("lb/ft3s",                 "kg/m3sec",
                                       16.01846337396013957962,      0 ),

# TURBULENCE FLUX
   "lb/sec2":    ("pound per second squared",
    "kg/sec2",                               0.45359237,             0 ),
   "lb/hr2":     ("pound per hour squared",
    "kg/sec2",                               0.00000003499941126543, 0 ),
   "kg/sec2":    ("kilogram per second squared",
    "kg/sec2",                               1,                      0 ),
   "kg/hr2":     ("kilogram per hour squared",
    "kg/sec2",                               0.00000007716049382716, 0 ),

# EDDY VISCOSITY TIME DERIVATIVE
   "mm2/sec2":   ("square millimeter per second square",
                  "m2/sec2",                 1e-6,                   0 ),
   "ft2/hr2":    ("square foot per hour square",   "m2/sec2",
                   0.00000000716844444444,                           0 ),
   "cm2/sec2":   ("square centimeter per second square",
                  "m2/sec2",                 1e-4,                   0 ),
   "m2/hr2":     ("square meter per hour square",  "m2/sec2",
		  0.00000007716049382716,                            0 ),
   "ft2/sec2":   ("square foot per second square", "m2/sec2",
                  0.09290304,                                        0 ),
   "m2/sec2":    ("square meter per second square","m2/sec2",
                  1,                                                 0 ),

# TEMPERATURE TIME DERIVATIVE
   "K/sec" : ("Kelvin per second",    "K/sec", 1,                      0 ),
   "K/hr"  : ("Kelvin per hour",      "K/sec", 0.00027777777777777777, 0 ),
   "oC/sec": ("Celcius per second",   "K/sec", 1,                      0 ),
   "oC/hr" : ("Celcius per hour",     "K/sec", 0.00027777777777777777, 0 ),
   "oF/sec": ("Fahrenheit per second","K/sec", 0.55555555555555555555, 0 ),
   "oF/hr" : ("Fahrenheit per hour",  "K/sec", 0.00015432098765432098, 0 ),

# DYADIC
   "lb-ft2": ("pound foot squared",     "kg-m2", 0.0421401100938048,   0 ),
   "kg-m2":  ("kilogram meter squared", "kg-m2", 1,                    0 ),

# AREA
   "m2":     ( "square meter",          "m2",    1,                 0   ),
   "cm2":    ( "square centimeter",     "m2",    1.e-04,            0   ),
   "acre":   ( "acre",                  "m2",    4046.856422,       0   ),
   "km2":    ( "square kilometer",      "m2",    1.e+6,             0   ),
   "mm2":    ( "square millimeter",     "m2",    1.e-06,            0   ),
   "ft2":    ( "square foot",           "m2",    0.09290304,        0   ),
   "inch2":  ( "square inch",           "m2",    0.00064516,        0   ),
   "mile2":  ( "square mile",           "m2",    2589988,           0   ),
   "yd2":    ( "square yard",           "m2",    0.83612736,        0   ),

# GRAD_PRESSURE

   "N/m3":      ( "newton per cubic meter",
                  "N/m3",                        1,                 0   ),
   "dyne/cm3":  ( "dyne per cubic centimeter",
                  "N/m3",                        10,                0   ),
   "pa/m":      ( "pascal per meter",
                  "N/m3",                        1,                 0   ),
   "pdl/ft3":   ( "Poundal per cubic foot",
                  "N/m3",                        4.87342,           0   ),
   "kgf/m3":    ( "kilogram-force per cubic meter",
                  "N/m3",                        9.80665,           0   ),
   "lbf/ft3":   ( "pound force per cube foot",
                  "N/m3",                        157.0874068,       0   ),
   "gf/cm3":    ( "gram-force per cubic centimeter",
                  "N/m3",                        1.e+04,            0   ),   
   "KPa/m":     ( "Kilo Pascal per meter",
                  "N/m3",                        1.e+03,            0   ),
   "lbf/inch3": ( "pound force per cube inch",
                  "N/m3",                        271447.039,        0   ),
   "PSI/inch":  ( "PSI per inch",
                  "N/m3",                        271447.039,        0   ),# PSI = lbf/inch2
   "N/cm3":     ( "newton per cubic centimeter",
                  "N/m3",                        1.e+06,            0   ),
   "kgf/cm3":   ( "kilogram-force per cubic centimeter",
                  "N/m3",                        9806650,           0   ),
   "bar/m":     ( "bar per meter",
                  "N/m3",                        1.e-05,            0   ),
   "atm/m":     ( "atmosphere per meter",
                  "N/m3",                        101325,            0   ),   
   "MPa/m":     ( "Mega Pascal per meter",
                  "N/m3",                        1.e+06,            0   ),
   "N/mm3":     ( "newton per cubic millimeter",
                  "N/m3",                        1.e+09,            0   ),
   "kgf/mm3":   ( "kilogram-force per cubic millimeter",
                  "N/m3",                        9806650000,        0   ),   
   
# VOLUME
   "m3":     ( "cubic meter",           "m3",    1,                 0   ),
   "dm3":    ( "cubic decimeter",       "m3",    1.e-03,            0   ),
   "cc":     ( "cubic centimeter",      "m3",    1.e-06,            0   ),
   "mm3":    ( "cubic millimeter",      "m3",    1.e-09,            0   ),
   "l":      ( "liter",                 "m3",    1.e-03,            0   ),
   "dl":     ( "deciliter",             "m3",    1.e-04,            0   ),
   "cl":     ( "centiliter",            "m3",    1.e-05,            0   ),   
   "ml":     ( "milliliter",            "m3",    1.e-06,            0   ),
   "ft3":    ( "cubic foot",            "m3",    0.02831684659,     0   ),
   "inch3":  ( "cubic inch",            "m3",    1.6387064e-05,     0   ),
   "yd3":    ( "cubic yard",            "m3",    0.764554858,       0   ),

# KINETIC_ENERGY
   "m2/sec2":( "square meter per square second",
               "m2/sec2",                        1,                 0   ),
   "ft2/sec2":( "square foot per square second",
                "m2/sec2",                       0.0929,            0   ),

# DISSIPATION
   "m2/sec3":( "square meter per cubic second",
               "m2/sec3",                        1,                 0   ),
   "ft2/sec3":( "square foot per cubic second",
                "m2/sec3",                       0.0929,            0   ),


# INVERSE_LENGTH
   "1/angstrom":( "inverse decinanometer",
                  "1/m",                         1.e+10,            0   ),
   "1/nm":      ( "inverse nanometer",
                  "1/m",                         1.e+09,            0   ),
   "1/micron":  ( "inverse micrometer",
                  "1/m",                         1.e+06,            0   ),
   "1/mil":     ( "inverse mil",
                  "1/m",                         39370.0787,        0   ),
   "1/mm":      ( "inverse millimeter",
                  "1/m",                         1.e+03,            0   ),
   "1/cm":      ( "inverse centimeter",
                  "1/m",                         1.e+02,            0   ),
   "1/inch":    ( "inverse inch",
                  "1/m",                         39.37008,          0   ),
   "1/ft":      ( "inverse foot",
                  "1/m",                         3.2808,            0   ),
   "1/yd":      ( "inverse yard",
                  "1/m",                         1.0936,            0   ),
   "1/m":       ( "inverse meter",
                  "1/m",                         1,                 0   ),
   "1/rd":      ( "inverse rod",
                  "1/m",                         0.1988,            0   ),
   "1/km":      ( "inverse kilomemter",
                  "1/m",                         1.e-03,            0   ),
   "1/mi":      ( "inverse mile",
                  "1/m",                         6.2137,            0   ),
   "1/nmile":   ( "inverse nautical mile",
                  "1/m",                         5.3996,            0   ),

# GRAD_TEMPERATURE

   "K/m":       ( "kelvin per meter",
                  "K/m",                         1,                 0   ),
   "oC/m":      ( "celsius per meter",
                  "K/m",                         1,                 0   ),
   "oF/inch":   ( "fahrenheit per inch",
                  "K/m",                         21.8723,           0   ),
   "oR/inch":   ( "rankine per inch",
                  "K/m",                         21.8723,           0   ),
   
# Permeability ; Panels 07/09 NP

   "m2":        ( "square meter",       "m2",    1,                 0   ),
   "cm2":       ( "square centimeter",  "m2",    1.e-04,            0   ),
   "micro_m2":  ( "square micrometer",  "m2",    1.e-12,            0   ),
   "D":         ( "Darcy",              "m2",    9.869233e-13,      0   ),
   "mD":        ( "milliDarcy",         "m2",    9.869233e-16,      0   ),

# Thermal resistance ; Misc. 12/09 D1 NP   

   "oC/W":      ( "celsius per watts",   "oC/W",  1,                0   ),

   "oF-hr/BTU (IT)":( "fahrenheit hour per Btu (IT)",               "oC/W",
                      0.527527926,                                  0   ),

   "oF-hr/BTU (th)":( "fahrenheit hour per Btu (th)",               "oC/W",
                      0.527175132,                                  0   ),

   "oF-sec/BTU (IT)":( "fahrenheit second per Btu (IT)",            "oC/W",
                      1899.100534716,                               0   ),

   "oF-sec/BTU (th)":( "fahrenheit second per Btu (th)",            "oC/W",
                      1897.83047608,                                0   ),
   
##   "K/W":       ( "kelvin per watts",   "K/W",  1,                  0   ),
##
##   "oF-hr/BTU (IT)":( "fahrenheit hour per Btu (IT)",               "K/W",
##                      0.527527926,                                  0   ),
##
##   "oF-hr/BTU (th)":( "fahrenheit hour per Btu (th)",               "K/W",
##                      0.527175132,                                  0   ),
##
##   "oF-sec/BTU (IT)":( "fahrenheit second per Btu (IT)",            "K/W",
##                      1899.100534716,                               0   ),
##
##   "oF-sec/BTU (th)":( "fahrenheit second per Btu (th)",            "K/W",
##                      1897.83047608,                                0   ),
   
}

#===========================================================================
# _untCats Table: A table that for each "category" will list the default
#                 (SI) unit, plus all the available units, sorted
#                 by magnitude.
#===========================================================================

_untCats        = {

   "acceleration":         (  "m/sec2",
                              ("ft/hr2",            "m/hr2",
                               "ft/min2",           "mm/sec2",
                               "gal",               "cm/sec2",
                               "in/sec2",           "ft/sec2",
                               "miles/hr2",
                               "m/sec2",            "grav",
                               "km/sec2",           "miles/sec2"    ) ),
   "angle":	           (  "deg",
                              ("second",            "minute",
                               "centrad",           "grad",
                               "deg",               "rad",
                               "quad",              "circle"        ) ),
   "angular_acceleration": ( "rad/sec2",
                             ("second/sec2",      "minute/sec2",
                              "deg/sec2",         "rad/sec2",
                              "quad/sec2",        "circle/sec2"      ) ),
   "angular_damping":      ( "kg-m2/sec",
                             ("lb-ft2/sec",       "kg-m2/sec"        ) ),

   "angular_stiffness":	   ( "kg-m2/sec2",
                             ("lb-ft2/sec2",      "kg-m2/sec2"       ) ),

   "angular_velocity":	   ( "rad/sec",
                             ("second/sec",       "minute/sec",
                              "deg/sec",          "rad/sec",
                              "quad/sec",         "circle/sec",
			      "RPM"				     ) ),

   "area":                 ( "m2",
                             ("acre",             "cm2",
                              "km2",              "m2",
                              "mm2",              "ft2",
                              "inch2",            "mile2",
                              "yd2",                                 ) ),

   "conductivity":	   ( "W/m-K",
                             ("W/(m2-K/cm)",      "BTU/(hr-ft2-oF/in)",
                              "KJ/hr-m-K",        "W/m-K",
                              "J/m-sec-K",        "Kcal/hr-m-oC",
                              "BTU/hr-ft-oF",     "W/(in2-oF/in)",
                              "W/cm-oC",          "cal/sec-cm-oC",
                              "KW/m-K",           "BTU/sec-ft-oF",
                              "MW/m-K"                               ) ),

   "convective_heat_flux": ( "J/m2-sec-K",
                             ("W/m2-K",
                              "KJ/hr-m2-K",       "J/m2-sec-K",
                              "Kcal/hr-m2-oC",    "BTU/hr-ft2-oF",
                              "W/in2-oF",         "W/cm2-oC",
                              "cal/sec-cm2-oC",   "KW/m2-K",
                              "BTU/sec-ft2-oF",   "MW/m2-K"          ) ),

   #"convective_species_flux": ("kg/m2-sec",                            ),
   "damping":	            ("kg/sec",
                             ("lb/day",           "g/min",
                              "kg/day",           "kg/hr",
                              "lb/hr",            "lb/min",
                              "g/sec",            "kg/min",
                              "lb/sec",           "kg/sec"          ) ),

   "density":	          ("kg/m3",
                            ("g/liter",                "kg/m3",
                             "SG(rel. Air)",            "lb/ft3",
                             "lb/UKgal",                "lb/USgal",
                             "slug/ft3",                "g/cm3",
                             "kg/liter",                "metricton/m3",
                             "SG(rel. Water)",          "oBaume",
                             "oAPI",                    "longton/yd3",
                             "lb/in3",                  "ton/ft3",
                             "kg/cm3"                                ) ),

   "diffusivity":            ("kg/m-sec",
                             ("kg/m-hr",              "lb/ft-hr",
                              "cP",                   "poise",
                              "g/cm-sec",             "dyne-sec/cm2",
                              "kg/m-sec",             "pa-sec",
                              "N-sec/m2",               "poundal-sec/ft2",
                              "lb/ft-sec",            "kgf-sec/m2",
                              "slugs/ft-sec",
                              "lbf-sec/ft2",          "lbf-sec/in2") ),
   
   #"direction":               ("dir",      (                         ) ),
   "displacement":	      ("m",
                               ("angstrom",                "nm",
                                "micron",                  "mil",
                                "mm",                      "cm",
                                "inch",                    "ft",
                                "yd",                      "m",
                                "rd",                      "km",
                                "mi",                      "nmile"   ) ),
   #"dyadic":	              ("kg-m2",    (                         ) ),
   "eddy_viscosity":	      ("m2/sec",
                              ("attostoke",          "femtostoke",
                               "picostoke",          "nanostoke",
                               "microstoke",         "millistoke",
                               "centistoke",         "mm2/sec",
                               "decistoke",          "cm2/sec",
                               "stoke",              "dekastoke",
                               "hectostoke",         "ft2/sec",
                               "kilostoke",          "m2/sec",
                               "megastoke",          "gigastoke",
                               "terastoke",          "petastoke",
                               "exastoke"                           ) ),
   "enthalpy":	              ("J/kg",
                              ("erg/g",             "J/kg",
                               "ft-lbf/lb",         "kgf-m/kg",
                               "J/g",               "MJ/tonne",
                               "kJ/kg",             "BTU/lb",
                               "cal/g",             "CHU/lb",
                               "kcal/kg",           "MJ/kg"         ) ),

   "flow_rate":	              ("m3/sec",
                              ("Mlit/day",          "lit/hr",
                               "barrel(oil)/day",   "gal(UK)/hr",
                               "barrel(oil)/hr",    "lit/min",
                               "ft3/min",           "m3/hr",
                               "gal(UK)/sec",       "lit/sec",
                               "ft3/sec",           "m3/sec",       
                               "gal(US)/hr",        "gal(US)/min",
			       "gal(US)/sec"			    ) ),

   "force":	              ("N",
                              ("dyne",                    "N",
                               "lbf"                                 ) ),
   "grad_pressure":	    ("N/m3",
                              ("dyne/cm3",          "N/m3",
                               "pa/m",              "pdl/ft3",
                               "kgf/m3",            "lbf/ft3",
                               "gf/cm3",            "KPa/m",
                               "lbf/inch3",         "PSI/inch",
                               "N/cm3",             "kgf/cm3",
                               "bar/m",             "atm/m",
                               "MPa/m",             "N/mm3",
                               "kgf/mm3"                            ) ),
   "grad_temperature":	    ("K/m",
                              ("K/m",              "oC/m",
                               "oF/inch",           "oR/inch"       ) ),
   "grad_velocity":	    ("1/sec",
                              ("1/yr",              "1/month",
                               "1/week",            "1/day",
                               "1/hr",              "1/min",
                               "1/sec",             "1/ms",
                               "1/us"                               ) ),
   "heat_flux":	            ("W/m2",
                              ("W/m2",              "kcal/m2-hr",
                               "BTU/ft2-hr",        "CHU/ft2-hr",
                               "pcu/ft2-hr",        "kcal/ft2-hr",
                               "KW/m2",             "W/cm2",
                               "BTU/ft2-sec",       "cal/cm2-sec"   ) ),
  "heat_rate":	            ("W",
                              ("BTU/hr",            "J/sec",
                               "W",                 "kcal/hr",
                               "cal/sec",           "BTU/min",
                               "kcal/min",          "kJ/sec",
                               "kW",                "BTU/sec",
                               "CHU/sec",           "kcal/sec",
                               "MJ/sec",            "MW"            ) ),

   #"heat_source":	      ("W/kg",     (                         ) ),
   "inverse_pressure":	      ("m2/N",
                              ("mm2/kgf",           "mm2/N",
                               "1/MPa",             "1/m Hg",
                               "1/atm",             "1/bar",
                               "cm2/kgf",           "1/ft Hg",
                               "cm2/N",             "1/m H2O",
                               "1/PSI",             "in2/lbf",
                               "1/in-mercury(32 oF)","1/in Hg",
                               "1/in-mercury(60 oF)","1/ft H2O",
                               "1/cm-mercury(0 oC)","1/cm Hg",
                               "1/KPa",             "1/in H2O",
                               "1/in-H2O (39.2 oF)","1/in-H2O (60 oF)",
                               "1/mm Hg",           "1/torr",
                               "1/mbar",            "cm2/gf",
                               "1/cm H2O",          "ft2/lbf",
                               "m2/kgf",            "1/mm H2O",
                               "ft2/pdl",           "1/pa",
                               "m2/N",              "cm2/dyne"      ) ),
   "inverse_temperature":     ("1/K",
                              ("1/K",               "1/oR",
                               "1/oC",              "1/oF",         ) ),
   "inverse_time":	      ("1/sec",
                              ("1/yr",              "1/month",
                               "1/week",            "1/day",
                               "1/hr",              "1/min",
                               "1/sec",             "1/ms",
                               "1/us"                               ) ),
   "inverse_length":          ("1/m",
                              ("1/angstrom",        "1/nm",
                               "1/micron",          "1/mil",
                               "1/mm",              "1/cm",
                               "1/inch",            "1/ft",
                               "1/yd",              "1/m",
                               "1/rd",              "1/km",
                               "1/mi",              "1/nmile",      ) ),
   "length":	              ("m",
                               ("angstrom",                "nm",
                                "micron",                  "mil",
                                "mm",                      "cm",
                                "inch",                    "ft",
                                "yd",                      "m",
                                "rd",                      "km",
                                "mi",                      "nmile"   ) ),

   "mass":                    ("kg",
                               ("mg",                      "gr",
                                "carat",                   "g",
                                "dr",                      "oz",
                                "ozt",                     "lb",
                                "kg",                      "slug",
                                "US ton",                  "shortton",
                                "ton",                     "metricton",
                                "Mg",                      "UK ton",
                                "longton"                             ) ),

   "mass_flux":	             ("kg/sec",
                              ("lb/day",        "kg/min",
                               "g/min",         "kg/day",
                               "g/sec",         "kg/hr",
                               "lb/hr",         "lb/min",
                               "lb/sec",        "kg/sec"               ) ),

   #"nondim":	             ("non-dim",   (                          ) ),


   "pressure":	             ("N/m2",
                              ("dyne/cm2",            "N/m2",
                               "pa",                  "pdl/ft2",
                               "mm H2O",              "kgf/m2",
                               "lbf/ft2",             "cm H2O",
                               "gf/cm2",              "mbar",
                               "torr",                "mm Hg",
                               "in-H2O (60 oF)",      "in-H2O (39.2 oF)",
                               "in H2O",              "KPa",
                               "cm Hg",               "cm-mercury(0 oC)",
                               "ft H2O",              "in-mercury(60 oF)",
                               "in Hg",               "in-mercury(32 oF)",
                               "lbf/in2",             "PSI",
                               "m H2O",               "N/cm2",
                               "ft Hg",               "kgf/cm2",
                               "bar",                 "atm",
                               "m Hg",                "MPa",
                               "N/mm2",               "kgf/mm2"       ) ),
   "specific_heat":	     ("J/kg-K",
                              ("erg/g-C",             "J/kg-K",
                               "m2/sec2-K",           "ft-lbf/lbm-F",
                               "J/g-k",               "J/g-C",
                               "cal/g-C",             "BTU/lb-F"      ) ),

   "stefan_boltzman":	     ("W/m2-K4",            ("W/m2-K4",       ) ),
   #"stiffness":	             ("kg/sec2",    (                 ) ),
   "stress":	             ("N/m2",
                              ("dyne/cm2",            "N/m2",
                               "pa",                  "pdl/ft2",
                               "kgf/m2",              "lbf/ft2",
                               "gf/cm2",              "mbar",
                               "torr",                "KPa",
                               "lbf/in2",             "PSI",
                               "N/cm2",               "kgf/cm2",
                               "bar",                 "atm",
                               "MPa",                 "N/mm2",
                               "kgf/mm2"                              ) ),

   "surface_tension":	     ("N/m",
                              ("dyn/cm",              "mN/m",
                               "gf/cm",               "N/m",
                               "lbf/ft",              "lbf/in"        ) ),


   "temperature":	     ("K",          ( "oR",    "oF",
                                               "K",    "oC"           ) ),

   "time":                   ("sec",
                             ("us",                   "ms",
                              "sec",                  "min",
                              "hr",                   "day",
                              "week",                 "month",
                              "yr"                                    ) ),
   "torque":	             ("N.m",
                              ("dyn.cm",              "gf.cm",
                               "mN.m",                "ozf.in",
                               "ozf.ft",              "lbf.in",
                               "N.m",                 "lbf.ft",
                               "kgf.m",               "kN.m"          ) ),
   #"turbulence_flux":	     ("kg/sec2",    (                         ) ),
   #"unknown":	             ("unknown",    (                         ) ),
   #"variable":	             ("var?",       (                         ) ),

   "velocity":	             ("m/sec",
                              ("cm/hr",               "in/hr",
                               "ft/hr",               "furlong/fortnight",
                               "cm/min",              "m/hr",
                               "in/min",              "mm/sec",
                               "ft/min",              "cm/sec",
                               "m/min",               "in/sec",
                               "km/hr",               "ft/sec",
                               "mile/hr",             "knots",
                               "yd/sec",              "m/sec",
                               "mach"                                 ) ),
   "viscosity":	            ("kg/m-sec",
                             ("kg/m-hr",              "lb/ft-hr",
                              "cP",                   "poise",
                              "g/cm-sec",             "dyne-sec/cm2",
                              "kg/m-sec",             "pa-sec",
                              "N-sec/m2",               "poundal-sec/ft2",
                              "lb/ft-sec",            "kgf-sec/m2",
                              "slugs/ft-sec",
                              "lbf-sec/ft2",          "lbf-sec/in2") ),
   "volume_heat_source":    ("W/m3",
                             ("erg/sec-cm3",            "W/m3",
                              "kcal/hr-m3",            "BTU/hr-ft3"   ) ),

# NEW VARIABLES: PRASHANT
   "mass_heat_source":       ("W/kg",
                             ("erg/sec-gm",            "W/kg",
                              "kcal/hr-kg",            "cal/sec-gm",
			      "BTU/hr-lb"   			      ) ),

   "species_flux":	     ("kg/m2sec",
                             ("g/hr-m2",           "g/min-m2",
                              "g/sec-cm2",         "kg/hr-m2",
                              "kg/hr-ft2",         "kg/m2sec",
                              "lb/hr-ft2",         "lb/min-ft2",
                              "lb/ft2sec"                             ) ),

   "volume_species_source":  ("kg/m3sec",
                             ("g/hr-m3",           "g/min-m3",
                              "g/sec-cm3",         "kg/hr-m3",
                              "kg/hr-ft3",         "kg/m3sec",
                              "lb/hr-ft3",         "lb/min-ft3",
                              "lb/ft3sec"                             ) ),

   "mass_species_source":    ("1/sec",
                             ("1/yr",              "1/week",
                              "1/day",             "1/hr",
                              "1/min",             "1/sec",
                              "1/ms"                                  ) ),

   "turbulence_flux":	     ("kg/sec2",
                             ("kg/sec2",           "kg/hr2",
                              "lb/sec2",           "lb/hr2",          ) ),

   "stiffness":		     ("kg/sec2",
                             ("kg/sec2",           "kg/hr2",
                              "lb/sec2",           "lb/hr2",          ) ),

   "radiation_heat_flux":    ("W/m2-K4",
                             ("W/m2-K4",                              ) ),

   "eddy_viscosity_time_derivative":	("m2/sec2",
                                        ("mm2/sec2",    "ft2/hr2",
                                         "cm2/sec2",    "m2/hr2",
                                         "ft2/sec2",    "m2/sec2"     ) ),

   "temperature_time_derivative":	("K/sec",
                                        ("K/sec",      "K/hr",
                                         "oC/sec",     "oC/hr",
                                         "oF/sec",     "oF/hr"        ) ),

   "dyadic":                            ("kg-m2",
                                        ("kg-m2",      "lb-ft2"       ) ),

   "area":                 ( "m2",
                             ("acre",             "cm2",
                              "km2",              "m2",
                              "mm2",              "ft2",
                              "inch2",            "mile2",
                              "yd2",                                 ) ),

   "volume":               ( "m3",
                             ("dm3",              "cc",
                              "mm3",              "l",
                              "dl",               "cl",
                              "ml",               "ft3",
                              "inch3",            "yd3",
                              "m3",                                  ) ),

   "kinetic_energy":       ( "m2/sec2",
                             ("ft2/sec2",         "m2/sec2"          ) ),

   "dissipation":          ( "m2/sec3",
                             ("ft2/sec3",         "m2/sec3"          ) ),

   "permeability":          ( "m2",
                             ("m2",             "cm2",
                              "micro_m2",       "D",
                              "mD"                                  ) ),

# Thermal resistance ; Misc. 12/09 D1 NP
##   "thermal_resistance":    ( "K/W",
##                             ("K/W",            "oF-hr/BTU (IT)",
##                              "oF-hr/BTU (th)", "oF-sec/BTU (IT)",
##                              "oF-sec/BTU (th)"                     ) ),

   "thermal_resistance":    ( "oC/W",
                             ("oC/W",           "oF-hr/BTU (IT)",
                              "oF-hr/BTU (th)", "oF-sec/BTU (IT)",
                              "oF-sec/BTU (th)"                     ) ),


}
